5 add custom term dates
CapSens/loan-creator pull request #20
Opened 2021-04-13 08:16 UTC by AJuliette

https://trello.com/c/XDFm1r4x/5-39-loancreator-ajout-de-la-possibilit%C3%A9-de-g%C3%A9n%C3%A9rer-un-%C3%A9ch%C3%A9ancier-en-sp%C3%A9cifiant-le-nombre-de-jours-de-chaque-%C3%A9ch%C3%A9ance

2021-04-21 13:56 UTC, AntoineBecquet requested changes
Pas mal de commentaires sur des détails, mais dans l'ensemble je pense que c'est bien organisé.

2021-04-21 13:56 UTC, AntoineBecquet commented on lib/loan_creator/common.rb
> +        end
On peut peut-être enlever la condition `if term_date.is_a?(Date)` et faire dans tous les cas `Date.parse(term_date.to_s)` ?

Si c'est déjà une date cela ne va rien changer, mais ça fait le même comportement pour tous les types de paramètres et une condition en moins à réfléchir ?

2021-04-21 13:56 UTC, AntoineBecquet commented on lib/loan_creator/common.rb
> +      TermDatesValidate.new(term_dates: v, duration_in_periods: @options[:duration_in_periods], interests_start_date: @options[:interests_start_date], loan_class: self.class.name)
Ligne trop longue.

Des exemples pour écrire les arguments sur plusieurs lignes :
https://github.com/rubocop/ruby-style-guide#no-double-indent

2021-04-21 13:56 UTC, AntoineBecquet commented on lib/loan_creator/common.rb
> +    def validate_term_dates(v)
Que signifie `v` ? 

Il faut éviter les abréviations pour les noms des variables/méthodes, à moins qu'elle soit très usuelle comme `id`.

2021-04-21 13:56 UTC, AntoineBecquet commented on lib/loan_creator/term_dates_validate.rb
> +    end
La méthode initialize est un constructeur : elle sert à initialiser l'instance de la classe et retourner celle-ci. Elle ne doit pas contenir d'autre logique.

Mais ici, je n'ai pas l'impression que c'est un objet dont on a besoin, mais uniquement une méthode. La classe TermDatesValidate semble pouvoir être remplacée par un module sans modifier son fonctionnement.

2021-04-21 13:56 UTC, AntoineBecquet commented on lib/loan_creator/term_dates_validate.rb
> +      end
En continuant sur l'idée du module, fais une petite méthode par validation, et passe les variable en paramètre plutôt que d'utiliser des variables d'instance, cela sera plus lisible.

2021-04-21 13:56 UTC, AntoineBecquet commented on lib/loan_creator/common.rb
> +      validate(:term_dates) { |v| validate_term_dates(v) } if term_dates?
La méthode `validate` (de la ligne 113) a-t-elle vraiment un intérêt à être appelée ici ? J'ai l'impression que ta méthode `validate_term_dates` lève déjà les exceptions attendues.

2021-04-21 13:56 UTC, AntoineBecquet commented on lib/loan_creator/term_dates_validate.rb
> +      true
Si les paramètres ne sont pas corrects des exceptions sont levées, et la valeur de retour de cette méthode n'a pas d'importance, donc je pense que ce `true` peut être supprimé ?

2021-04-21 13:56 UTC, AntoineBecquet commented on lib/loan_creator/term_dates_validate.rb
> +          raise ArgumentError, "term dates can't be more than 1 year apart. #{error_description}"
Pourquoi pas en vrai ? 
Si la personne qui utilise la gem veut capitaliser des intérêts, elle doit passer en paramètre les dates où cette capitalisation est faite, et cette capitalisation ne sera probablement pas faite moins d'une fois par an, mais pourquoi l'interdire ?

2021-05-03 07:32 UTC, AJuliette commented on lib/loan_creator/term_dates_validate.rb
> +          raise ArgumentError, "term dates can't be more than 1 year apart. #{error_description}"
C'est dans la spec

2021-05-05 13:00 UTC, AJuliette commented on lib/loan_creator/term_dates_validate.rb
> +          raise ArgumentError, "term dates can't be more than 1 year apart. #{error_description}"
@AntoineBecquet

2021-05-05 14:41 UTC, AntoineBecquet approved these changes

2021-05-05 14:45 UTC, AntoineBecquet requested changes
Ah mais du coup en pensant à la release je me rends compte qu'il manque quelque chose d'important : la documentation.

Il faut expliquer dans le readme comment cette feature s'utilise.

Et si en même temps tu peux bumper la version (`0.9.0` je pense là) et remplir le changelog je n'aurai plus qu'à merger et push sur rubygems.

2021-05-07 08:20 UTC, AntoineBecquet approved these changes

2021-05-07 08:20 UTC, merged