6 repayment due interests for non bullet
CapSens/loan-creator pull request #22
Opened 2021-04-29 09:29 UTC by AJuliette

https://trello.com/c/E0I98rDr/6-loan-non-bullet-avec-int%C3%A9r%C3%AAts-capitalis%C3%A9s-de-d%C3%A9part-devrait-capitaliser-les-interets-capitalis%C3%A9s

2021-04-29 12:00 UTC, AntoineBecquet requested changes

2021-04-29 12:14 UTC, AJuliette commented on spec/support/a_valid_lender_timetable.rb
> +    {due_on: {display_method: proc { |term| term.due_on.strftime("%d/%m/%Y") }}}
Pardooooooooon

2021-04-29 12:14 UTC, AJuliette commented on spec/support/a_valid_lender_timetable.rb
> +    {due_on: {display_method: proc { |term| term.due_on.strftime("%d/%m/%Y") }}}
J'ai oublié de recommenter

2021-04-30 08:09 UTC, AntoineBecquet approved these changes

2021-05-05 08:28 UTC, merged