2/initial term values
CapSens/loan-creator pull request #7
Opened 2020-11-17 16:54 UTC by Kernael

2020-11-17 17:17 UTC, AntoineBecquet requested changes

2020-11-17 17:17 UTC, AntoineBecquet commented on lib/loan_creator/common.rb
> +      @index                              = @index || nil
`@index = @index || nil`, `@index ||= nil`, donc rien en fait... 🤔 
À moins qu'il y ait une confusion avec `@starting_index` ?

2020-11-17 17:17 UTC, AntoineBecquet commented on lib/loan_creator/common.rb
>      end
Comment ça se comporte avec `interests_start_date` et l'existence d'un term zéro ?

Je me dis que les options n'ont pas de sens à être utilisées ensemble, mais peut être que ça marche ? Ou faut-il interdire de les utiliser ensemble ?

2020-11-17 17:17 UTC, AntoineBecquet commented on spec/loan_creator/in_fine_spec.rb
> +      }
Donner des valeurs valeurs aux variables qu'on gère, histoire de toutes les tester d'un coup, et enlever `capitalized_interests` qu'on ne gère pas ?

2020-11-19 08:19 UTC, Kernael commented on lib/loan_creator/common.rb
>      end
Je ne comprends pas à quoi correspond le term zéro. Est-ce-que ces cas ont été testés ?

2020-11-19 09:08 UTC, Kernael commented on spec/loan_creator/in_fine_spec.rb
> +      }
J'ai ajouté des tests sur deux autres types de Loan pour que ça couvre toutes les options

2020-11-19 14:45 UTC, AntoineBecquet approved these changes

2020-11-19 14:46 UTC, merged